Fix -Wnontrivial-memcall warning
Memcall functions work at the byte level so they don't know about C++
semantics and these C++ objects might not have trivial
constructors or destructors. I silenced the warning by explicitly
casting the pointer to void* with static_cast. I did this fix because I
assume the code developer knows the consequences with using memcall
functions with C++ objects.

packages/modules/adb/fastdeploy/deploypatchgenerator/deploy_patch_generator.cpp:222:16:
error: first argument in call to 'memcpy' is a pointer to non-trivially
copyable type 'md5Digest' (aka 'pair<unsigned long, unsigned long>')
[-Werror,-Wnontrivial-memcall]
  222 |         memcpy(&md5, deviceEntry.md5().data(),
deviceEntry.md5().size());
      |                ^

packages/modules/adb/fastdeploy/deploypatchgenerator/deploy_patch_generator.cpp:232:16:
error: first argument in call to 'memcpy' is a pointer to non-trivially
copyable type 'md5Digest' (aka 'pair<unsigned long, unsigned long>')
[-Werror,-Wnontrivial-memcall]
  232 |         memcpy(&md5, localEntry.md5().data(),
localEntry.md5().size());
      |                ^

Flag: Flag: EXEMPT warning bugfix
Bug: 430598176
Test: m & presubmits
Change-Id: I854a986bf6a27c4a2e64e15ee559533ae80ad058